from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('admin-dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('list-users/', ListUsers.as_view(), name='list_users'),
    path('list-tutors/', ListTutors.as_view(), name='list_tutors'),
    path('list-courses/', ListCoursesView.as_view(), name='list_courses'),
    path('status/', UserStatus.as_view(), name='status'),
    path('tutor-status/', TutorStatus.as_view(), name='tutor-status'),
    path('course-status/<str:id>/', CourseStatusView.as_view(), name='course-status'),
    path('set-draft/<str:id>/', SetCourseDraftView.as_view(), name='set_draft'),
    path('list-applicaions/', ListApplicationsView.as_view(), name='list_applicaions'),
    path('list-course-request/', CourseRequestsView.as_view(), name='list_course_request'),
    path('applications/', TutorApplicationView.as_view(), name='applications'),
    path('create-category/', CreateCategoryView.as_view(), name='create_category'),
    path('edit-category/<str:id>/', EditCategoryView.as_view(), name='edit_category'),
    path('list-category/', ListCategoryView.as_view(), name='list_category'),
    path('category-status/', CategoryStatusView.as_view(), name='category_status'),
    path('create-plan/', CreatePlanView.as_view(), name='create_plan'),
    path('list-plan/', ListPlanView.as_view(), name='list_plan'),
    path('application-view/<str:id>/', TutorApplicationsOverView.as_view(), name='application_view'),
    path('tutor-view/<str:userId>/', TutorOverView.as_view(), name='tutor_view'),
    path('view-course/<str:id>/', CourseOverView.as_view(), name='view_course'),
    path('course-modules/<str:id>/', ListCourseModulesView.as_view(), name='course_modules'),
    path('view-module/<str:id>/', ModuleDetailView.as_view(), name='view_module'),
    path('course-lessons/<str:id>/', ListCourseLessonView.as_view(), name='course_lessons'),
    path('lesson-overview/<str:lessonId>/', LessonOverview.as_view(), name='lesson_overview'),
    path('accept-application/<str:applicationId>/', AcceptApplicationView.as_view(), name='accept_application'),
    path('reject-application/<str:applicationId>/', RejectApplicationView.as_view(), name='reject_application'),
    path('rejected-reason/<str:id>/', RejectedReasonView.as_view(), name="rejected_reason"),
    path('accept-course-request/<str:courseId>/', AcceptCourseRequestView.as_view(), name='accept_course_request'),
    path('reject-course-request/<str:courseId>/', RejectCourseRequestView.as_view(), name='reject_course_request'),
    path('accept-module/<str:id>/', AcceptModuleView.as_view(), name='accept_module'),
    path('reject-module/<str:id>/', RejectModuleView.as_view(), name='reject_module'),
    path('accept-lesson/<str:lessonId>/', AcceptLessonView.as_view(), name='accept_lesson'),
    path('reject-lesson/<str:lessonId>/', RejectLessonView.as_view(), name='reject_lesson'),
    path('module-status/<str:id>/', ModuleStatusView.as_view(), name='module_status'),
    path('lesson-status/<str:lessonId>/', LessonStatusView.as_view(), name='lesson_status'),
    path('reports/', ReportsView.as_view(), name='reports'),
    path('tutor/<str:id>/reports/', TutorReportMarkView.as_view(), name='tutor_reports'),
    path('course/<str:id>/reports/', CourseReportMarkView.as_view(), name='course_reports'),
    path('platform-wallet/', PlatformWalletView.as_view(), name='platform-wallet/'),
    path('payout-requests/', PayoutRequestsListView.as_view(), name='payout-requests/'),
    path('payout-request-details/<str:id>/', PayoutRequestDetailsView.as_view(), name='payout-request-details/'),
    path('approve-payout-request/<str:id>/', ApprovePayoutRequestView.as_view(), name='approve-payout-request/'),
    path('reject-payout-request/<str:id>/', RejectPayoutRequestView.as_view(), name='reject-payout-request//'),
]   