# Generated by Django 5.1.7 on 2025-12-22 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_rooms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('completed', 'Completed')], default='missed', max_length=10)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='chat.chatroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room'], name='chat_callse_room_id_cf72c5_idx'), models.Index(fields=['caller'], name='chat_callse_caller__05f43f_idx'), models.Index(fields=['callee'], name='chat_callse_callee__8e24e6_idx'), models.Index(fields=['status'], name='chat_callse_status_23f2a9_idx'), models.Index(fields=['started_at'], name='chat_callse_started_63a252_idx'), models.Index(fields=['caller', 'status'], name='chat_callse_caller__6bd74a_idx'), models.Index(fields=['room', 'started_at'], name='chat_callse_room_id_7fce0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('call', 'Call')], default='text', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['room'], name='chat_messag_room_id_cee780_idx'), models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'), models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'), models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'), models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_645da7_idx'), models.Index(fields=['sender', 'is_read'], name='chat_messag_sender__7ea760_idx')],
            },
        ),
    ]
