# Generated by Django 5.1.7 on 2025-12-20 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['room'], name='chat_callse_room_id_cf72c5_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller'], name='chat_callse_caller__05f43f_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['callee'], name='chat_callse_callee__8e24e6_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status'], name='chat_callse_status_23f2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['started_at'], name='chat_callse_started_63a252_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', 'status'], name='chat_callse_caller__6bd74a_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['room', 'started_at'], name='chat_callse_room_id_7fce0a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='chat_chatro_created_914abe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room'], name='chat_messag_room_id_cee780_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_645da7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'is_read'], name='chat_messag_sender__7ea760_idx'),
        ),
    ]
