# Generated by Django 5.1.7 on 2025-03-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
