# Generated by Django 5.1.7 on 2025-04-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_accounts_profile_picture'),
        ('adminpanel', '0011_plan_alter_tutorapplications_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.plan')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.tutordetails')),
            ],
        ),
    ]
