# Generated by Django 5.1.7 on 2025-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_tutorsubscription_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
