# Generated by Django 5.1.7 on 2025-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_accounts_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
