# Generated by Django 5.1.7 on 2025-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_accounts_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='google_signed',
            field=models.BooleanField(default=False),
        ),
    ]
