# Generated by Django 5.1.7 on 2025-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_accounts_google_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
