# Generated by Django 5.1.7 on 2025-05-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_accounts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='leetcode_id',
        ),
    ]
