# Generated by Django 5.1.7 on 2025-05-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_remove_accounts_leetcode_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='google_signed',
            new_name='google_verified',
        ),
    ]
