# Generated by Django 5.1.7 on 2025-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_rename_google_signed_accounts_google_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
