# Generated by Django 5.1.7 on 2025-05-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_accounts_rating_accounts_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='review_count',
        ),
    ]
