# Generated by Django 5.1.7 on 2025-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_remove_accounts_rating_remove_accounts_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetails',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
