# Generated by Django 5.1.7 on 2025-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_moduleprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
