# Generated by Django 5.1.7 on 2025-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_moduleprogress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
