# Generated by Django 5.1.7 on 2025-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_lessonprogress_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
