# Generated by Django 5.1.7 on 2025-06-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_chatroom_callsession_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
