# Generated by Django 5.1.7 on 2025-07-08 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_remove_chatroom_participants_remove_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetails',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
