# Generated by Django 5.1.7 on 2025-11-14 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0026_alter_tutordetails_account'),
        ('tutorpanel', '0019_alter_meetings_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='tutorpanel.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to='Accounts.tutordetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_tutor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='tutorpanel.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_rating',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TutorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ratings', to='Accounts.tutordetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_tutor_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_rating',
                'ordering': ['-created_at'],
                'unique_together': {('tutor', 'user')},
            },
        ),
    ]
