# Generated by Django 5.1.7 on 2025-11-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0027_coursereview_tutorreview_courserating_tutorrating'),
        ('tutorpanel', '0019_alter_meetings_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tutorrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tutorrating',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorreview',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorreview',
            name='user',
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tutorpanel.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_feedback',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Accounts.tutordetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_feedback',
                'unique_together': {('tutor', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='CourseRating',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='TutorRating',
        ),
        migrations.DeleteModel(
            name='TutorReview',
        ),
    ]
