# Generated by Django 5.1.7 on 2025-11-14 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_remove_coursereview_course_remove_coursereview_user_and_more'),
        ('tutorpanel', '0019_alter_meetings_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tutorpanel.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_reports',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TutorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Accounts.tutordetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_reports',
                'unique_together': {('tutor', 'user')},
            },
        ),
    ]
