# Generated by Django 5.1.7 on 2025-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_coursereport_tutorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereport',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorreport',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
