# Generated by Django 5.1.7 on 2025-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_coursereport_is_marked_tutorreport_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetails',
            name='phone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
