# Generated by Django 5.1.7 on 2025-12-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_tutordetails_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
