# Generated by Django 5.1.7 on 2025-12-15 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
