# Generated by Django 5.1.7 on 2025-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_tutorsubscription_created_at'),
        ('adminpanel', '0026_remove_platformwallet_balance'),
        ('tutorpanel', '0022_meetings_course'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['email'], name='Accounts_ac_email_5e435b_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['role'], name='Accounts_ac_role_8c8dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['created_at'], name='Accounts_ac_created_2f715a_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['isblocked'], name='Accounts_ac_isblock_3fd918_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['google_verified'], name='Accounts_ac_google__880c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['role', 'isblocked'], name='Accounts_ac_role_64af2e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['course'], name='course_feed_course__cb4538_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['user'], name='course_feed_user_id_c2a8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['created_at'], name='course_feed_created_42695e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['course', 'created_at'], name='course_feed_course__aca3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['course'], name='course_repo_course__614291_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['user'], name='course_repo_user_id_f0102c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['is_marked'], name='course_repo_is_mark_5aeb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['created_at'], name='course_repo_created_2abee8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['course', 'is_marked'], name='course_repo_course__e70ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user'], name='Accounts_le_user_id_b18c71_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='Accounts_le_lesson__8d42b4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['status'], name='Accounts_le_status_c510cc_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['completed'], name='Accounts_le_complet_9726fe_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'status'], name='Accounts_le_user_id_b1ae40_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='Accounts_le_lesson__17157c_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['user'], name='Accounts_mo_user_id_1778f6_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module'], name='Accounts_mo_module__bfc839_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['status'], name='Accounts_mo_status_842b97_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['user', 'status'], name='Accounts_mo_user_id_1a3990_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module', 'status'], name='Accounts_mo_module__668286_idx'),
        ),
        migrations.AddIndex(
            model_name='tutordetails',
            index=models.Index(fields=['status'], name='Accounts_tu_status_9f063c_idx'),
        ),
        migrations.AddIndex(
            model_name='tutordetails',
            index=models.Index(fields=['account'], name='Accounts_tu_account_8ca6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorfeedback',
            index=models.Index(fields=['tutor'], name='tutor_feedb_tutor_i_9f2728_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorfeedback',
            index=models.Index(fields=['user'], name='tutor_feedb_user_id_a5e632_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorfeedback',
            index=models.Index(fields=['created_at'], name='tutor_feedb_created_cce6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorfeedback',
            index=models.Index(fields=['tutor', 'created_at'], name='tutor_feedb_tutor_i_4b337a_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorreport',
            index=models.Index(fields=['tutor'], name='tutor_repor_tutor_i_731376_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorreport',
            index=models.Index(fields=['user'], name='tutor_repor_user_id_bd9daf_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorreport',
            index=models.Index(fields=['is_marked'], name='tutor_repor_is_mark_65f54d_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorreport',
            index=models.Index(fields=['created_at'], name='tutor_repor_created_16e93b_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorreport',
            index=models.Index(fields=['tutor', 'is_marked'], name='tutor_repor_tutor_i_715b27_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsubscription',
            index=models.Index(fields=['tutor'], name='Accounts_tu_tutor_i_b06fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsubscription',
            index=models.Index(fields=['is_active'], name='Accounts_tu_is_acti_1d5515_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsubscription',
            index=models.Index(fields=['expires_on'], name='Accounts_tu_expires_4c38f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsubscription',
            index=models.Index(fields=['tutor', 'is_active'], name='Accounts_tu_tutor_i_700fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['user'], name='Accounts_us_user_id_068192_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['course'], name='Accounts_us_course__fe52fc_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['status'], name='Accounts_us_status_095c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['enrolled_on'], name='Accounts_us_enrolle_5849ad_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['user', 'status'], name='Accounts_us_user_id_14ccf0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['course', 'status'], name='Accounts_us_course__0553fc_idx'),
        ),
    ]
