# Generated by Django 5.1.7 on 2025-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_accounts_accounts_ac_email_5e435b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
