# Generated by Django 5.1.7 on 2025-12-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_tutorsubscription_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsubscription',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='Accounts.tutordetails'),
        ),
    ]
