from django.urls import path
from .views import *


urlpatterns = [
    path('tutor-dashboard/', TutorDashboardView.as_view(), name='tutor_dashboard'),
    path('tutor-profile/', TutorProfileView.as_view(), name='tutor_profile'),
    path('subscription-history/', SubscriptionHistoryView.as_view(), name='subscription_history'),
    path('tutor-subscribed/', TutorSubscribedCheckView.as_view(), name='tutor_subscribed'),
    path('tutor-application/', TutorApplicationCheckView.as_view(), name='tutor_application'),
    path('edit-tutor/', EditTutorView.as_view(), name='edit_tutor'),
    path('profile-picture/', UploadTutorProfilePictureView.as_view(), name='profile_picture/'),
    path('fetch-tutor/<str:id>/', FetchTutorView.as_view(), name='fetch-tutor'),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    path('edit-course/<str:id>/', EditCourseView.as_view(), name='edit_course'),
    path('course-status/<str:id>/', CourseStatusView.as_view(), name='course_status'),
    path('list-course/', ListCourseView.as_view(), name='list_course'),
    path('view-course/<str:id>/', CourseOverView.as_view(), name='view_course'),
    path('create-module/', CreateModuleView.as_view(), name='create_module'),
    path('edit-module/<str:id>/', EditModuleView.as_view(), name='edit_module'),
    path('course-modules/<str:id>/', ListCourseModulesView.as_view(), name='course_modules'),
    path('module-status/<str:id>/', ModuleStatusView.as_view(), name='module_status'),
    path('view-module/<str:id>/', ModuleDetailView.as_view(), name='view_module'),
    path('course-lessons/<str:id>/', ListCourseLessonView.as_view(), name='course_lessons'),
    path('create-lesson/', CreateLessonView.as_view(), name='create_lesson`'),
    path('edit-lesson/<str:pk>/', EditLessonView.as_view(), name='edit_lesson`'),
    path('lesson-status/<str:lessonId>/', LessonStatusView.as_view(), name='lesson_status'),
    path('set-draft/<str:id>/', SetCourseDraftView.as_view(), name='set_draft'),
    path('course-rejections/', CourseRejectionHistoryView.as_view(), name='course_rejections'),
    path('module-rejections/<str:course_id>/', ModuleRejectionHistoryView.as_view(), name='module_rejections'),
    path('lesson-rejections/<str:module_id>/', LessonRejectionHistoryView.as_view(), name='lesson_rejections'),
    path('active-courses/', ActiveCoursesListView.as_view(), name='active-courses/'),
    path('shedule-meeting/', SheduleMeetingView.as_view(), name='shedule-meeting'),
    path('edit-meeting/', EditMeetingView.as_view(), name='edit-meeting'),
    path('delete-meeting/', DeleteMeetingView.as_view(), name='delete-meeting'),
    path('sheduled-meetings/', SheduledMeetings.as_view(), name='sheduled-meetings/'),
    path('recent-meetings/', RecentMeetingsView.as_view(), name='recent-meetings/'),
    path('get_levels/', get_course_levels, name='get_levels'),
    path('course-monthly-trends/<str:id>/', CourseMonthlyTrendsView.as_view(), name="course-monthly-trends"),
    path('wallet-dashboard/', WalletDashboardView.as_view(), name='wallet-dashboard/'),
    path('payout-requests/', PayoutRequestListView.as_view(), name='payout-requests/'),
    path('request-payout/', PayoutRequestView.as_view(), name='request_payout/'),
    path('cancel-payout/', PayoutCancelView.as_view(), name='cancel_payout/'),
]