# Generated by Django 5.1.7 on 2025-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_tutorapplications_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplications',
            name='verification',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='tutorapplications',
            name='verification_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
