# Generated by Django 5.1.7 on 2025-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_tutorapplications_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplications',
            name='verification',
        ),
        migrations.AddField(
            model_name='tutorapplications',
            name='verification_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
