# Generated by Django 5.1.7 on 2025-03-24 12:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_tutorapplications_verification_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplications',
            name='verification_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplications',
            name='verification_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
