# Generated by Django 5.1.7 on 2025-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_tutorapplications_verification_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplications',
            name='verification_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplications',
            name='verification_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
