# Generated by Django 5.1.7 on 2025-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_tutorapplications_verification_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplications',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
