# Generated by Django 5.1.7 on 2025-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_tutorapplications_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
