# Generated by Django 5.1.7 on 2025-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_tutorapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplications',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
