# Generated by Django 5.1.7 on 2025-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_plan_alter_tutorapplications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
