# Generated by Django 5.1.7 on 2025-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_plan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
