# Generated by Django 5.1.7 on 2025-11-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_tutorrejectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplications',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
