# Generated by Django 5.1.7 on 2025-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_lessonrejectionhistory_modulerejectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
