# Generated by Django 5.1.7 on 2025-12-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_payoutrequest'),
        ('tutorpanel', '0021_remove_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorpanel.wallet'),
        ),
    ]
