# Generated by Django 5.1.7 on 2025-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_platformwallet_platformwallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
