# Generated by Django 5.1.7 on 2025-12-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_alter_platformwallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformwallet',
            name='balance',
        ),
    ]
