# Generated by Django 5.1.7 on 2025-12-20 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_accounts_accounts_ac_email_5e435b_idx_and_more'),
        ('adminpanel', '0026_remove_platformwallet_balance'),
        ('tutorpanel', '0022_meetings_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['is_active'], name='adminpanel__is_acti_23d1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['created_at'], name='adminpanel__created_965879_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['is_active', 'created_at'], name='adminpanel__is_acti_fd1e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='courserejectionhistory',
            index=models.Index(fields=['course'], name='adminpanel__course__13a45f_idx'),
        ),
        migrations.AddIndex(
            model_name='courserejectionhistory',
            index=models.Index(fields=['created_at'], name='adminpanel__created_500626_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrejectionhistory',
            index=models.Index(fields=['lesson'], name='adminpanel__lesson__be580a_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrejectionhistory',
            index=models.Index(fields=['created_at'], name='adminpanel__created_bf596e_idx'),
        ),
        migrations.AddIndex(
            model_name='modulerejectionhistory',
            index=models.Index(fields=['module'], name='adminpanel__module__d3c123_idx'),
        ),
        migrations.AddIndex(
            model_name='modulerejectionhistory',
            index=models.Index(fields=['created_at'], name='adminpanel__created_2e7fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['tutor'], name='adminpanel__tutor_i_fdcb74_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status'], name='adminpanel__status_32bec9_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['requested_at'], name='adminpanel__request_5da62a_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['tutor', 'status'], name='adminpanel__tutor_i_a42234_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'requested_at'], name='adminpanel__status_6e2dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='adminpanel__is_acti_6667bd_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_type'], name='adminpanel__plan_ty_4e32c7_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_category'], name='adminpanel__plan_ca_2a8df9_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'plan_type'], name='adminpanel__is_acti_d39811_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['wallet'], name='adminpanel__wallet__eaba1d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['transaction_type'], name='adminpanel__transac_9bd69c_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['created_at'], name='adminpanel__created_f927a2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['user'], name='adminpanel__user_id_2dc60c_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['tutor'], name='adminpanel__tutor_i_044117_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallettransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='adminpanel__transac_f6d474_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorapplications',
            index=models.Index(fields=['status'], name='adminpanel__status_157b06_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorapplications',
            index=models.Index(fields=['account'], name='adminpanel__account_e62638_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorapplications',
            index=models.Index(fields=['created_at'], name='adminpanel__created_c4f7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorapplications',
            index=models.Index(fields=['email'], name='adminpanel__email_303634_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorapplications',
            index=models.Index(fields=['status', 'created_at'], name='adminpanel__status_3eb462_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrejectionhistory',
            index=models.Index(fields=['application'], name='adminpanel__applica_e5e980_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrejectionhistory',
            index=models.Index(fields=['created_at'], name='adminpanel__created_dad5eb_idx'),
        ),
    ]
