from django.urls import path
from .views import *

urlpatterns = [
    path('signup/', UserRegisterView.as_view(), name='signup'),
    path('google-verified/<str:email>/', GoogleVerifiedCheckView.as_view(), name='google_verified'),
    path('login/', LoginView.as_view(), name='login'),
    path("google-login/", GoogleLoginView.as_view(), name="google-login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forgot-password/<str:email>/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password/<str:uidb64>/<str:token>/', ResetPasswordView.as_view(), name='reset-password'),
    path('user-dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user-profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile-picture/', UploadUserProfilePictureView.as_view(), name='profile_picture'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('tutor-home/', TutorHomeView.as_view(), name='tutor_home'),
    path('courses/', ListCourseView.as_view(), name='courses'),
    path("categories/", ListCategoriesView.as_view(), name="categories"),
    path('check-enrollment/', CheckUserEnrollmentView.as_view(), name='check-user-enrollment'),
    path('check-tutor/<str:course_id>/', CheckCourseTutor.as_view(), name='check-tutor'),
    path("course-details/<str:id>/", CourseDetailsView  .as_view(), name="course_details"),
    path("tutor-details/<str:id>/", TutorDetailsView  .as_view(), name="tutor_details"),
    path('edit-user/', EditUserView.as_view(), name='edit_user'),
    path('verify-otp/', OTPVerificationView.as_view(), name='verify_otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend_otp'),
    path("token/refresh/", CustomTokenRefreshView.as_view(), name="token_refresh"),
    path('create-checkout-session/<int:plan_id>/', CreateCheckoutSessionView.as_view(), name='create-checkout'),
    path('stripe-success/', StripeSuccessView.as_view(), name='stripe-success'),
    path('subscription-cancel/', CancelTutorSubscriptionView.as_view(), name='stripe-success'),
    path("payment_verification/", PaymentVerificationView.as_view(), name="payment_verification"),
    path("paypal_success/", PayPalSuccessView.as_view(), name="paypal_success"),
    path("enrolled-courses/", EnrolledCoursesView.as_view(), name="enrolled_courses"),
    path("start-course/<str:id>/", StartCourseView.as_view(), name="start_course"),
    path("started-course/<str:id>/", StartedCourseDetailsView.as_view(), name="started_course"),
    path("course-tutor/<str:id>/", CourseTutorView.as_view(), name="course_tutor"),
    path("course-modules/", StartedCourseModulesView.as_view(), name="course_modules"),
    path("start-module/", StartModuleView.as_view(), name="start_module"),
    path("started-module/<str:id>/", StartedModuleDetailsView.as_view(), name="started_module"),
    path("started-module-lessons/", StartedModuleLessonsView.as_view(), name="started_module_lessons"),
    path("start-lesson/", StartLessonView.as_view(), name="start_lesson"),
    path("started-lesson/<str:id>/", StartedLessonDetailsView.as_view(), name="started_lesson"),
    path("complete-lesson/", CompleteLessonView.as_view(), name="complete_lesson"),
    path("certificate/<int:course_id>/", GenerateCertificateView.as_view(), name="generate_certificate"),
    path("available-meetings/", AvailableMeetingsView.as_view(), name="available-meetings/"),
    path("booked-meetings/", BookedMeetingsView.as_view(), name="booked-meetings/"),
    path('book-meeting/', BookMeetingView.as_view(), name='book-meeting'),
    path('cancel-meeting/', CancelMeetingView.as_view(), name='cancel-meeting'),
    path('recent-meetings/', RecentMeetingsView.as_view(), name='recent-meetings/'),
    path("tutor/feedback/", TutorFeedbackView.as_view(), name="tutor-feedback-create"),
    path("tutor/<int:tutor_id>/feedback/", TutorFeedbackView.as_view(), name="tutor-feedback-list-delete"),
    path("course/feedback/", CourseFeedbackView.as_view(), name="course-feedback-create"),
    path("course/<int:course_id>/feedback/", CourseFeedbackView.as_view(), name="course-feedback-list-delete"),
    path("tutor/report/", TutorReportView.as_view()),               
    path("tutor/<int:tutor_id>/report/", TutorReportView.as_view()), 
    path("course/report/", CourseReportView.as_view()),             
    path("course/<int:course_id>/report/", CourseReportView.as_view()), 
]