from django.urls import path
from .views import *
from .stripe_webhook import StripeWebhookView

urlpatterns = [
    path('signup/', UserRegisterView.as_view(), name='signup'),
    path('google_verified/<str:email>/', GoogleVerifiedCheckView.as_view(), name='google_verified'),
    path('login/', LoginView.as_view(), name='login'),
    path("google-login/", GoogleLoginView.as_view(), name="google-login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forgot_password/<str:email>/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset_password/<str:uidb64>/<str:token>/', ResetPasswordView.as_view(), name='reset-password'),
    path('user_dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile_picture/', UploadUserProfilePictureView.as_view(), name='profile_picture'),
    path('webhook/stripe/', StripeWebhookView.as_view(), name='stripe-webhook'),
    path('tutor_home/', TutorHomeView.as_view(), name='tutor_home'),
    path('courses/', ListCourseView.as_view(), name='courses'),
    path("categories/", ListCategoriesView.as_view(), name="categories"),
    path('check_enrollment/', CheckUserEnrollmentView.as_view(), name='check-user-enrollment'),
    path("course_details/<str:id>/", CourseDetailsView  .as_view(), name="course_details"),
    path("tutor_details/<str:id>/", TutorDetailsView  .as_view(), name="tutor_details"),
    path('edit_user/', EditUserView.as_view(), name='edit_user'),
    path('verify_otp/', OTPVerificationView.as_view(), name='verify_otp'),
    path('resend_otp/', ResendOTPView.as_view(), name='resend_otp'),
    path("token/refresh/", CustomTokenRefreshView.as_view(), name="token_refresh"),
    path('create-checkout-session/<int:plan_id>/', CreateCheckoutSessionView.as_view(), name='create-checkout'),
    path('stripe-success/', StripeSuccessView.as_view(), name='stripe-success'),
    path("payment_verification/", PaymentVerificationView.as_view(), name="payment_verification"),
    path("paypal_success/", PayPalSuccessView.as_view(), name="paypal_success"),
    path("enrolled_courses/", EnrolledCoursesView.as_view(), name="enrolled_courses"),
    path("start_course/<str:id>/", StartCourseView.as_view(), name="start_course"),
    path("started_course/<str:id>/", StartedCourseDetailsView.as_view(), name="started_course"),
    path("course_tutor/<str:id>/", CourseTutorView.as_view(), name="course_tutor"),
    path("course_modules/", StartedCourseModulesView.as_view(), name="course_modules"),
    path("start_module/", StartModuleView.as_view(), name="start_module"),
    path("started_module/<str:id>/", StartedModuleDetailsView.as_view(), name="started_module"),
    path("started_module_lessons/", StartedModuleLessonsView.as_view(), name="started_module_lessons"),
    path("start_lesson/", StartLessonView.as_view(), name="start_lesson"),
    path("started_lesson/<str:id>/", StartedLessonDetailsView.as_view(), name="started_lesson"),
    path("complete_lesson/", CompleteLessonView.as_view(), name="complete_lesson"),
    path("certificate/<int:course_id>/", GenerateCertificateView.as_view(), name="generate_certificate"),
    path("available-meetings/", AvailableMeetingsView.as_view(), name="available-meetings/"),
    path("booked-meetings/", BookedMeetingsView.as_view(), name="booked-meetings/"),
    path('book-meeting/', BookMeetingView.as_view(), name='book-meeting'),
    path('recent-meetings/', RecentMeetingsView.as_view(), name='recent-meetings/'),
]