# Generated by Django 5.1.7 on 2025-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0002_rename_tutor_course_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
