# Generated by Django 5.1.7 on 2025-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0005_course_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='approved',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
