# Generated by Django 5.1.7 on 2025-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0007_modules_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
