# Generated by Django 5.1.7 on 2025-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0008_lessons_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
