# Generated by Django 5.1.7 on 2025-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0009_lessons_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
