# Generated by Django 5.1.7 on 2025-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0011_course_rating_course_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='review',
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
