# Generated by Django 5.1.7 on 2025-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0012_remove_course_review_course_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='review_count',
        ),
    ]
