# Generated by Django 5.1.7 on 2025-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0013_remove_course_rating_remove_course_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
