# Generated by Django 5.1.7 on 2025-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0015_meetings_meetingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='left',
            field=models.PositiveBigIntegerField(default=5),
            preserve_default=False,
        ),
    ]
