# Generated by Django 5.1.7 on 2025-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0016_meetings_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
