# Generated by Django 5.1.7 on 2025-08-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0017_meetings_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='meeting_completed',
            field=models.BooleanField(default=False),
        ),
    ]
