# Generated by Django 5.1.7 on 2025-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0018_meetingbooking_meeting_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
