# Generated by Django 5.1.7 on 2025-12-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0021_remove_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorpanel.course'),
        ),
    ]
