# Generated by Django 5.1.7 on 2025-12-20 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_accounts_accounts_ac_email_5e435b_idx_and_more'),
        ('adminpanel', '0027_coursecategory_adminpanel__is_acti_23d1a5_idx_and_more'),
        ('tutorpanel', '0022_meetings_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by'], name='tutorpanel__created_05eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category_id'], name='tutorpanel__categor_cdab38_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='tutorpanel__status_d974cf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='tutorpanel__is_acti_8180de_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_draft'], name='tutorpanel__is_draf_cd7faa_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='tutorpanel__created_461dde_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_active'], name='tutorpanel__status_aa6aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by', 'status'], name='tutorpanel__created_70e359_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'is_draft'], name='tutorpanel__is_acti_1d34b7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['created_by'], name='tutorpanel__created_6c8504_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['module'], name='tutorpanel__module__e39ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['status'], name='tutorpanel__status_681ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['is_active'], name='tutorpanel__is_acti_750c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['created_at'], name='tutorpanel__created_c897f0_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['module', 'status'], name='tutorpanel__module__ee3010_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['status', 'is_active'], name='tutorpanel__status_1e557d_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['meeting'], name='tutorpanel__meeting_7e75a1_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['user'], name='tutorpanel__user_id_72d176_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['meeting_completed'], name='tutorpanel__meeting_8a44d3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['booked_at'], name='tutorpanel__booked__f5c890_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['meeting', 'meeting_completed'], name='tutorpanel__meeting_692981_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingbooking',
            index=models.Index(fields=['user', 'meeting_completed'], name='tutorpanel__user_id_305384_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['tutor'], name='tutorpanel__tutor_i_d47c34_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['course'], name='tutorpanel__course__edcaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['date'], name='tutorpanel__date_6d4e86_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['is_completed'], name='tutorpanel__is_comp_d31fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['created_at'], name='tutorpanel__created_49fe49_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['tutor', 'is_completed'], name='tutorpanel__tutor_i_b00600_idx'),
        ),
        migrations.AddIndex(
            model_name='meetings',
            index=models.Index(fields=['date', 'is_completed'], name='tutorpanel__date_ab7226_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['created_by'], name='tutorpanel__created_c42b60_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['course'], name='tutorpanel__course__a13a24_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['status'], name='tutorpanel__status_e7343d_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['is_active'], name='tutorpanel__is_acti_7ef058_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['created_at'], name='tutorpanel__created_fab40e_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['course', 'status'], name='tutorpanel__course__d38253_idx'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['status', 'is_active'], name='tutorpanel__status_37253c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['tutor'], name='tutorpanel__tutor_i_9de099_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_freeze'], name='tutorpanel__is_free_8a0159_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet'], name='tutorpanel__wallet__5dd73a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='tutorpanel__created_33c267_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='tutorpanel__wallet__e0387d_idx'),
        ),
    ]
