# Generated by Django 5.1.7 on 2026-01-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorpanel', '0023_course_tutorpanel__created_05eb7d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
